services:
  - type: web
    name: whatsapp2-chat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true
    ports:
      - port: 10000
        protocol: HTTP
      - port: 8765
        protocol: WebSocket
